config/routes.rb
Rails.application.routes.draw do

  namespace 'admin' do
    resources 'user_search', only: [:index, :create]
  end
  scope module: 'admin' do
    resources :airlines do
      collection do
        get 'autocomplete_airline_name'
      end
    end
    resources :airports do
      get 'autocomplete_airport_name', :on => :collection
    end
    resources :requirement_defs
  end

  namespace 'campdoc' do
    resource :sso, only: [:create]
    resources :profiles, only: [:create, :destroy] do
      get 'completed'
      post 'destroy'
    end
  end
  
  resources :dashboard, only: [:index]
  namespace 'dashboard' do
    resources :payment, only: [:new]
    resources :summer_contact, only: [:index]
    resources :summer_faq, only: [:index]
    namespace 'transportation' do
      resources :carpool_list, only: [:index]
      resources :bus_list, only: [:index]
    end
  end

  namespace 'docusign' do
    resources :requirements, only: [:show, :destroy]
    resources :pdfs, only: [:show]
    resources :results, only: [:show]
  end

  namespace :flights do
    resource :lookup, only: [:create]
  end

  scope module: 'forms' do
    resources :arrival_forms, :only => [:edit, :show, :update]
    resources :ambassador_forms, :only => [:edit, :show, :update]
    resources :course_forms, :only => [:edit, :show, :update]
    resources :departure_forms, :only => [:edit, :show, :update]
    resources :housing_forms, :only => [:edit, :show, :update]
    resources :parent_eval_forms, :only => [:edit, :show, :update]
    resources :stay_late_forms, only: [:index, :update] do
      collection do
        get 'fm'
      end
    end
    resources :student_tech_forms, :only => [:edit, :show, :update]
  end

  resources :profiles do
    member do
      get 'login_as'
      get 'reset_password'
      get 'resend_welcome'
    end
  end

  resources :requirements, only: [:index, :update]
  resources :sessions, only: [:new, :create, :destroy]

  namespace :users do
    resources :profile_associations, only: [:new, :create]
  end
  resources :users, only: [:update, :destroy] do
    collection do
      post 'batch_update'
    end
  end

  get 'forms_home' => 'requirements#index', :as => :forms_home
  get 'forgot_password' => 'sessions#forgot_password', :as => :forgot_password
  post 'forgot_password' => 'sessions#forgot_password'
  get 'login' => 'sessions#new', :as => :login
  get 'login/:token' => 'sessions#create_from_email'
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'reset_password(/:token)' => 'sessions#reset_password', :as => :reset_password
  post 'reset_password' => 'sessions#reset_password'
  get 'select_user' => 'sessions#select_user', :as => :select_user

  root :to => 'dashboard#index'
  #root :to => 'sessions#maintenance'
end

app/models/airline.rb
class Airline < ActiveRecord::Base
  def display_name
    "#{self.name} (#{self.icao})"
  end
end

app/controllers/admin/airlines_controller.rb
class Admin::AirlinesController < ApplicationController
  autocomplete :airline, :name, :display_value => :display_name, :extra_data => [:icao]#, :full => true
  before_action :check_admin, except: [:autocomplete_airline_name]
  before_action :set_airline, only: [:show, :edit, :update, :destroy]
  layout 'basic'

  # GET /airlines
  # GET /airlines.json
  def index
    @airlines = Airline.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @airlines }
    end
  end

  # GET /airlines/1
  # GET /airlines/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @airline }
    end
  end

  # GET /airlines/new
  # GET /airlines/new.json
  def new
    @airline = Airline.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @airline }
    end
  end

  # GET /airlines/1/edit
  def edit
  end

  # POST /airlines
  # POST /airlines.json
  def create
    @airline = Airline.new(airline_params)

    respond_to do |format|
      if @airline.save
        format.html { redirect_to airline_url(@airline), notice: 'Airline was successfully created.' }
        format.json { render json: @airline, status: :created, location: @airline }
      else
        format.html { render action: "new" }
        format.json { render json: @airline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /airlines/1
  # PUT /airlines/1.json
  def update
    respond_to do |format|
      if @airline.update_attributes(airline_params)
        format.html { redirect_to airline_url(@airline), notice: 'Airline was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @airline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airlines/1
  # DELETE /airlines/1.json
  def destroy
    @airline.destroy

    respond_to do |format|
      format.html { redirect_to airlines_url }
      format.json { head :no_content }
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_airline
    @airline = Airline.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def airline_params
    params.require(:airline).permit(:icao, :short_name, :name, :callsign, :country, :url, :location)
  end
end

app/views/admin/airlines/_form.html.erb
<%= form_for @airline do |f| %>
  <% if @airline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@airline.errors.count, "error") %> prohibited this airline from being saved:</h2>

      <ul>
      <% @airline.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :icao %><br />
    <%= f.text_field :icao %>
  </div>
  <div class="field">
    <%= f.label :short_name %><br />
    <%= f.text_field :short_name %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :callsign %><br />
    <%= f.text_field :callsign %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_area :url %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/airlines/edit.html.erb
<h1>Editing airline</h1>

<%= render 'form' %>

<%= link_to 'Show', airline_path(@airline) %> |
<%= link_to 'Back', airlines_path %>

app/views/admin/airlines/index.html.erb
<h1>Listing airlines</h1>

<table>
  <tr>
    <th>Icao</th>
    <th>Short name</th>
    <th>Name</th>
    <th>Callsign</th>
    <th>Country</th>
    <th>Url</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @airlines.each do |airline| %>
  <tr>
    <td><%= airline.icao %></td>
    <td><%= airline.short_name %></td>
    <td><%= airline.name %></td>
    <td><%= airline.callsign %></td>
    <td><%= airline.country %></td>
    <td><%= airline.url %></td>
    <td><%= airline.location %></td>
    <td><%= link_to 'Show', airline_path(airline) %></td>
    <td><%= link_to 'Edit', edit_airline_path(airline) %></td>
    <td><%= link_to 'Destroy', airline_path(airline), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Airline', new_airline_path %>

app/views/admin/airlines/new.html.erb
<h1>New airline</h1>

<%= render 'form' %>

<%= link_to 'Back', airlines_path %>

app/views/admin/airlines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Icao:</b>
  <%= @airline.icao %>
</p>

<p>
  <b>Short name:</b>
  <%= @airline.short_name %>
</p>

<p>
  <b>Name:</b>
  <%= @airline.name %>
</p>

<p>
  <b>Callsign:</b>
  <%= @airline.callsign %>
</p>

<p>
  <b>Country:</b>
  <%= @airline.country %>
</p>

<p>
  <b>Url:</b>
  <%= @airline.url %>
</p>

<p>
  <b>Location:</b>
  <%= @airline.location %>
</p>


<%= link_to 'Edit', edit_airline_path(@airline) %> |
<%= link_to 'Back', airlines_path %>