config/routes.rb
Rails.application.routes.draw do

  namespace 'admin' do
    resources 'user_search', only: [:index, :create]
  end
  scope module: 'admin' do
    resources :airlines do
      collection do
        get 'autocomplete_airline_name'
      end
    end
    resources :airports do
      get 'autocomplete_airport_name', :on => :collection
    end
    resources :requirement_defs
  end

  namespace 'campdoc' do
    resource :sso, only: [:create]
    resources :profiles, only: [:create, :destroy] do
      get 'completed'
      post 'destroy'
    end
  end
  
  resources :dashboard, only: [:index]
  namespace 'dashboard' do
    resources :payment, only: [:new]
    resources :summer_contact, only: [:index]
    resources :summer_faq, only: [:index]
    namespace 'transportation' do
      resources :carpool_list, only: [:index]
      resources :bus_list, only: [:index]
    end
  end

  namespace 'docusign' do
    resources :requirements, only: [:show, :destroy]
    resources :pdfs, only: [:show]
    resources :results, only: [:show]
  end

  namespace :flights do
    resource :lookup, only: [:create]
  end

  scope module: 'forms' do
    resources :arrival_forms, :only => [:edit, :show, :update]
    resources :ambassador_forms, :only => [:edit, :show, :update]
    resources :course_forms, :only => [:edit, :show, :update]
    resources :departure_forms, :only => [:edit, :show, :update]
    resources :housing_forms, :only => [:edit, :show, :update]
    resources :parent_eval_forms, :only => [:edit, :show, :update]
    resources :stay_late_forms, only: [:index, :update] do
      collection do
        get 'fm'
      end
    end
    resources :student_tech_forms, :only => [:edit, :show, :update]
  end

  resources :profiles do
    member do
      get 'login_as'
      get 'reset_password'
      get 'resend_welcome'
    end
  end

  resources :requirements, only: [:index, :update]
  resources :sessions, only: [:new, :create, :destroy]

  namespace :users do
    resources :profile_associations, only: [:new, :create]
  end
  resources :users, only: [:update, :destroy] do
    collection do
      post 'batch_update'
    end
  end

  get 'forms_home' => 'requirements#index', :as => :forms_home
  get 'forgot_password' => 'sessions#forgot_password', :as => :forgot_password
  post 'forgot_password' => 'sessions#forgot_password'
  get 'login' => 'sessions#new', :as => :login
  get 'login/:token' => 'sessions#create_from_email'
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'reset_password(/:token)' => 'sessions#reset_password', :as => :reset_password
  post 'reset_password' => 'sessions#reset_password'
  get 'select_user' => 'sessions#select_user', :as => :select_user

  root :to => 'dashboard#index'
  #root :to => 'sessions#maintenance'
end

app/models/airport.rb
class Airport < ActiveRecord::Base
  def display_name
    "#{self.name} (#{self.icao})"
  end
end

app/controllers/admin/airports_controller.rb
class Admin::AirportsController < ApplicationController
  autocomplete :airport, :name, :display_value => :display_name, :extra_data => [:icao], :full => true

  before_action :check_admin, except: [:autocomplete_airport_name]
  before_action :set_airport, only: [:show, :edit, :update, :destroy]

  layout 'basic'


  # GET /airports
  # GET /airports.json
  def index
    @airports = Airport.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @airports }
    end
  end

  # GET /airports/1
  # GET /airports/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @airport }
    end
  end

  # GET /airports/new
  # GET /airports/new.json
  def new
    @airport = Airport.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @airport }
    end
  end

  # GET /airports/1/edit
  def edit
  end

  # POST /airports
  # POST /airports.json
  def create
    @airport = Airport.new(airport_params)

    respond_to do |format|
      if @airport.save
        format.html { redirect_to airport_url(@airport), notice: 'Airport was successfully created.' }
        format.json { render json: @airport, status: :created, location: @airport }
      else
        format.html { render action: "new" }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /airports/1
  # PUT /airports/1.json
  def update
    respond_to do |format|
      if @airport.update_attributes(airport_params)
        format.html { redirect_to airport_url(@airport), notice: 'Airport was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airports/1
  # DELETE /airports/1.json
  def destroy
    @airport.destroy

    respond_to do |format|
      format.html { redirect_to airports_url }
      format.json { head :no_content }
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_airport
    @airport = Airport.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def airport_params
    params.require(:airport).permit(:icao, :latitude, :location, :longitude, :name, :timezone)
  end
end

app/views/admin/airports/_form.html.erb
<%= form_for(@airport) do |f| %>
  <% if @airport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@airport.errors.count, "error") %> prohibited this airport from being saved:</h2>

      <ul>
      <% @airport.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :icao %><br />
    <%= f.text_field :icao %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :timezone %><br />
    <%= f.text_field :timezone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/airports/edit.html.erb
<h1>Editing airport</h1>

<%= render 'form' %>

<%= link_to 'Show', airports_path(@airport) %> |
<%= link_to 'Back', airports_path %>

app/views/admin/airports/index.html.erb
<h1>Listing airports</h1>

<table>
  <tr>
    <th>Icao</th>
    <th>Latitude</th>
    <th>Location</th>
    <th>Longitude</th>
    <th>Name</th>
    <th>Timezone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @airports.each do |airport| %>
  <tr>
    <td><%= airport.icao %></td>
    <td><%= airport.latitude %></td>
    <td><%= airport.location %></td>
    <td><%= airport.longitude %></td>
    <td><%= airport.name %></td>
    <td><%= airport.timezone %></td>
    <td><%= link_to 'Show', airport_path(airport) %></td>
    <td><%= link_to 'Edit', edit_airport_path(airport) %></td>
    <td><%= link_to 'Destroy', airport_path(airport), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Airport', new_airport_path %>

app/views/admin/airports/new.html.erb
<h1>New airport</h1>

<%= render 'form' %>

<%= link_to 'Back', airports_path %>

app/views/admin/airports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Icao:</b>
  <%= @airport.icao %>
</p>

<p>
  <b>Latitude:</b>
  <%= @airport.latitude %>
</p>

<p>
  <b>Location:</b>
  <%= @airport.location %>
</p>

<p>
  <b>Longitude:</b>
  <%= @airport.longitude %>
</p>

<p>
  <b>Name:</b>
  <%= @airport.name %>
</p>

<p>
  <b>Timezone:</b>
  <%= @airport.timezone %>
</p>


<%= link_to 'Edit', edit_airport_path(@airport) %> |
<%= link_to 'Back', airports_path %>