config/routes.rb
Rails.application.routes.draw do

  namespace 'admin' do
    resources 'user_search', only: [:index, :create]
  end
  scope module: 'admin' do
    resources :airlines do
      collection do
        get 'autocomplete_airline_name'
      end
    end
    resources :airports do
      get 'autocomplete_airport_name', :on => :collection
    end
    resources :requirement_defs
  end

  namespace 'campdoc' do
    resource :sso, only: [:create]
    resources :profiles, only: [:create, :destroy] do
      get 'completed'
      post 'destroy'
    end
  end
  
  resources :dashboard, only: [:index]
  namespace 'dashboard' do
    resources :payment, only: [:new]
    resources :summer_contact, only: [:index]
    resources :summer_faq, only: [:index]
    namespace 'transportation' do
      resources :carpool_list, only: [:index]
      resources :bus_list, only: [:index]
    end
  end

  namespace 'docusign' do
    resources :requirements, only: [:show, :destroy]
    resources :pdfs, only: [:show]
    resources :results, only: [:show]
  end

  namespace :flights do
    resource :lookup, only: [:create]
  end

  scope module: 'forms' do
    resources :arrival_forms, :only => [:edit, :show, :update]
    resources :ambassador_forms, :only => [:edit, :show, :update]
    resources :course_forms, :only => [:edit, :show, :update]
    resources :departure_forms, :only => [:edit, :show, :update]
    resources :housing_forms, :only => [:edit, :show, :update]
    resources :parent_eval_forms, :only => [:edit, :show, :update]
    resources :stay_late_forms, only: [:index, :update] do
      collection do
        get 'fm'
      end
    end
    resources :student_tech_forms, :only => [:edit, :show, :update]
  end

  resources :profiles do
    member do
      get 'login_as'
      get 'reset_password'
      get 'resend_welcome'
    end
  end

  resources :requirements, only: [:index, :update]
  resources :sessions, only: [:new, :create, :destroy]

  namespace :users do
    resources :profile_associations, only: [:new, :create]
  end
  resources :users, only: [:update, :destroy] do
    collection do
      post 'batch_update'
    end
  end

  get 'forms_home' => 'requirements#index', :as => :forms_home
  get 'forgot_password' => 'sessions#forgot_password', :as => :forgot_password
  post 'forgot_password' => 'sessions#forgot_password'
  get 'login' => 'sessions#new', :as => :login
  get 'login/:token' => 'sessions#create_from_email'
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'reset_password(/:token)' => 'sessions#reset_password', :as => :reset_password
  post 'reset_password' => 'sessions#reset_password'
  get 'select_user' => 'sessions#select_user', :as => :select_user

  root :to => 'dashboard#index'
  #root :to => 'sessions#maintenance'
end

app/controllers/admin/user_search_controller.rb
class Admin::UserSearchController < ApplicationController
  before_action :check_admin

  layout 'basic'

  # GET /admin/user_search/
  def index
    @users = []
  end

  # POST /admin/user_search
  def create
    query = params[:query]
    reg_query = Regexp.quote query

    @users = []
    User.all.each do |user|
      @users << user if (user.information.match(/#{reg_query}/i))
    end

    Profile.all.each do |profile|
      profile.users.each{|u|@users << u} if (profile.email.match(/#{reg_query}/i))
    end

    @users = @users.sort_by { |s| "#{s.get_key('last_name')}#{s.get_key('first_name')}" }.uniq
    
    respond_to do |format|
      format.js { render :javascript => @users }
    end

  end
end

app/views/admin/user_search/_user.html.erb
<tr class='striped--near-white'>
  <td class="pv1 ph2">
    <%= h user.get_key 'first_name' %> <%= h user.get_key 'last_name' %>
  </td>
  <td class="pv1 ph2 f6">
    <% user.profiles.each_with_index do |p, i| %>
      <% if i > 0 %><br><% end %>
      <%= link_to p.email, login_as_profile_path(id: p.id, user_id: user.id), class: xc('link') %>
      • <%= link_to "change pass", reset_password_profile_path(id: p.id), class: xc('link') %>
      • <%= link_to "resend welcome", resend_welcome_profile_path(id: p.id, user_id: user.id), class: xc('link') %>
    <% end %>
  </td>
</tr>

app/views/admin/user_search/_users.html.erb
<table id="user-search-list">
  <thead>
    <tr class="tl">
      <th class="pl2">Name</th>
      <th class="pl2">Profiles</th>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => 'admin/user_search/user', :collection => @users %>
  </tbody>
</table>

app/views/admin/user_search/create.js.erb
$('#user-search-list').replaceWith('<%=j render :partial => 'admin/user_search/users', :object => @users %>');

app/views/admin/user_search/index.html.erb
<h1 class="<%= xc('h2') %>">Portal Users Search</h1>

<%= form_tag '/admin/user_search', method: :post, remote: true, class: xc('form', replace: {"w5" => "w-100"}) do %>
  <div class="dib">
    <%= label_tag 'query', "Search Name or Email", class: xc('label') %>
    <%= text_field_tag 'query', '', placeholder: "search", class: xc('input-text') %>
  </div>
  <div class="dib mt2 mt0-ns ml3-ns ">
    <%= submit_tag 'search', class: xc('btn') %>
  </div>
<% end %>

<div class="mt3">
  <%= render :partial => 'users', :object => @users %>
</div>